### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by xipasduarte** [goblindegook/WordPress-Plugin-Boilerplate-NS#1]
On the initial setup, when running: `composer install`
```
[RuntimeException]
  Could not load package phpspec/prophecy in http://packagist.org: [UnexpectedValueE
  xception] Could not parse version constraint ^1.0.2: Invalid version string "^1.0.
  2"
```

**Comment by xipasduarte** [comment]
Using `"phpunit/phpunit": "4.4.*"`, before `phpunit` required the above package, installs without any issues.

**Comment by goblindegook** [comment]
Works for me, I'm afraid. Running `composer install` on a clean clone, it installs `phpunit/phpunit` 4.6.4 and `phpspec/prophecy` 1.4.0.

Maybe try running `composer clear-cache`?

**Comment by xipasduarte** [comment]
The problem was with the composer version. Ran `composer self-update` and the version was bumped to `1.0-dev (1cb427ff5c0b977468643a39436f3b0a356fc8eb)` for which the error does not occur.

Maybe a note can be added on the README to alert if any similar issues arise.
